import React, { useState } from 'react';
import type {
  PracticeAttempt,
  PracticeSessionDefinition,
  EvidenceLog,
  TopicSkillState,
  Topic,
  TaskDefinition,
  TaskProgress,
  DSAProblem,
  DSAProgress,
  DSAAttempt,
} from '../../types';
import {
  summarizePracticeAnswers,
  isObjectiveQuestionType,
} from '../../engine/practiceEngine';
import {
  buildProjectDefenseTrace,
  type EvidenceCatalog,
} from '../../engine/evidenceTrace';
import {
  Award,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Play,
  ChevronDown,
  ChevronUp,
  FileCheck,
  ArrowRight,
  ShieldCheck,
  Clock,
} from 'lucide-react';

interface ProjectEvidenceLedgerProps {
  practiceAttempts: PracticeAttempt[];
  practiceSessions: PracticeSessionDefinition[];
  evidenceLogs: EvidenceLog[];
  skillStates: Record<string, TopicSkillState>;
  topics?: Topic[];
  taskDefinitions?: TaskDefinition[];
  taskProgress?: Record<string, TaskProgress>;
  dsaProblems?: DSAProblem[];
  dsaProgress?: Record<string, DSAProgress>;
  dsaAttempts?: DSAAttempt[];
  todayISO?: string;
  onLaunchDefense: () => void;
  onNavigateToRemediation: (route: string, targetId?: string) => void;
}

export const ProjectEvidenceLedger: React.FC<ProjectEvidenceLedgerProps> = ({
  practiceAttempts,
  practiceSessions,
  evidenceLogs,
  skillStates,
  topics = [],
  taskDefinitions = [],
  taskProgress = {},
  dsaProblems = [],
  dsaProgress = {},
  dsaAttempts = [],
  todayISO = new Date().toISOString().slice(0, 10),
  onLaunchDefense,
  onNavigateToRemediation,
}) => {
  const [reviewAttemptId, setReviewAttemptId] = useState<string | null>(null);

  const projectAttempts = practiceAttempts.filter(
    (a) => a.category === 'project_defense'
  );
  const latestAttempt = projectAttempts[0] ?? null;
  const passedAttempts = projectAttempts.filter((a) => a.passed === true);

  // Build canonical EvidenceTrace using the authoritative engine function
  const catalog: EvidenceCatalog = {
    topics,
    taskDefinitions,
    taskProgress,
    dsaProblems,
    dsaProgress,
    dsaAttempts,
    evidenceLogs,
    practiceSessions,
    practiceAttempts,
    skillStates,
    todayISO,
  };

  const defenseTrace = buildProjectDefenseTrace(catalog);

  return (
    <div
      className="bg-[#111713] border border-[#28352D] rounded-[6px] p-5 sm:p-6 space-y-5"
      data-testid="project-evidence-ledger"
      role="region"
      aria-label="Proof-of-Work Verification Ledger"
    >
      {/* Zone 5 Header & Telemetry */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#28352D] pb-4">
        <div className="space-y-0.5">
          <div className="flex items-center gap-2">
            <span className="text-[10px] font-mono uppercase tracking-widest px-2 py-0.5 bg-[#0D9488]/15 text-[#2DD4BF] rounded border border-[#0D9488]/30 font-bold">
              Zone 5 · Verification Ledger
            </span>
            <span className="text-xs font-mono text-foreground-muted">
              Proof-of-Work Audit Trail
            </span>
          </div>
          <h2 className="text-base sm:text-lg font-bold text-foreground tracking-tight flex items-center gap-2">
            <Award className="size-4 text-[#0D9488]" />
            <span>Verifiable Project Defense Attempt Ledger</span>
          </h2>
          <p className="text-xs text-foreground-muted">
            Append-only historical verification records generated by defense simulation runs.
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap sm:flex-nowrap shrink-0">
          <span className="text-xs font-mono px-2.5 py-1 rounded bg-[#161E19] text-[#2DD4BF] border border-[#0D9488]/30 font-semibold">
            {projectAttempts.length} Recorded Run{projectAttempts.length === 1 ? '' : 's'}
          </span>
          <span className="text-xs font-mono px-2.5 py-1 rounded bg-[#161E19] text-status-success border border-status-success/30 font-semibold">
            {passedAttempts.length} Passed
          </span>
        </div>
      </div>

      {/* Causal Evidence Traceability Bar */}
      <div className="p-3.5 bg-[#161E19] border border-[#28352D] rounded-[6px] flex flex-col md:flex-row md:items-center justify-between gap-3 text-xs">
        <div className="space-y-1 max-w-2xl">
          <div className="flex items-center gap-2">
            <ShieldCheck className="size-3.5 text-[#0D9488]" />
            <span className="font-mono font-bold text-foreground uppercase tracking-wider text-[11px]">
              Evidence Traceability Contract
            </span>
            <span className="text-[10px] font-mono px-1.5 py-0.2 rounded bg-[#111713] text-foreground-muted border border-[#28352D]">
              origin: {defenseTrace.origin}
            </span>
          </div>
          <p className="text-[11px] text-foreground-muted leading-relaxed" data-testid="trace-explanation">
            {defenseTrace.why}
          </p>
        </div>

        <div className="flex items-center gap-2 shrink-0 pt-2 md:pt-0 border-t md:border-t-0 border-[#28352D] text-[11px] font-mono text-secondary">
          <span>Credit:</span>
          <span className="text-[#2DD4BF] font-semibold bg-[#111713] px-2 py-0.5 rounded border border-[#28352D]">
            prep-interview-career (+round(Score × 0.2))
          </span>
        </div>
      </div>

      {/* Empty State vs Attempt History */}
      {projectAttempts.length === 0 ? (
        <div
          className="p-8 text-center bg-[#161E19] border border-[#28352D] rounded-[6px] space-y-4"
          data-testid="project-evidence-empty"
        >
          <div className="size-12 rounded-full bg-[#111713] border border-[#28352D] flex items-center justify-center mx-auto text-secondary">
            <Award className="size-6" />
          </div>
          <div className="space-y-1 max-w-md mx-auto">
            <h3 className="text-sm font-bold text-foreground">
              No Recorded Defense Proof Yet
            </h3>
            <p className="text-xs text-foreground-muted leading-relaxed">
              No project defense attempts have been recorded. Launch a defense simulation to evaluate your architecture knowledge and append verifiable proof-of-work.
            </p>
          </div>
          <button
            type="button"
            onClick={onLaunchDefense}
            className="inline-flex items-center gap-2 px-4 py-2.5 rounded-[4px] bg-[#0D9488] hover:bg-[#14B8A6] text-[#F0FDFA] text-xs font-semibold tracking-wide transition-all shadow-xs cursor-pointer focus-visible:ring-2 focus-visible:ring-[#2DD4BF]"
          >
            <Play className="size-3.5 fill-current" />
            <span>Launch Project Defense</span>
          </button>
        </div>
      ) : (
        <div className="space-y-3.5" data-testid="project-evidence-list">
          {/* Truthful Next Action Banner (Derived from latest attempt) */}
          {latestAttempt && (
            <div
              className={`p-3.5 sm:p-4 border rounded-[6px] text-xs flex flex-col sm:flex-row sm:items-center justify-between gap-3 ${
                latestAttempt.passed
                  ? 'bg-status-success/10 border-status-success/30 text-status-success'
                  : 'bg-status-warning/10 border-status-warning/30 text-status-warning'
              }`}
              data-testid="project-next-action"
            >
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  {latestAttempt.passed ? (
                    <CheckCircle2 className="size-4 shrink-0 text-status-success" />
                  ) : (
                    <AlertTriangle className="size-4 shrink-0 text-status-warning" />
                  )}
                  <span className="font-bold text-xs uppercase tracking-wider font-mono">
                    {latestAttempt.passed
                      ? latestAttempt.passingScorePct !== undefined
                        ? `Defense Passed — ${latestAttempt.scorePct}% meets the ${latestAttempt.passingScorePct}% threshold.`
                        : `Defense Recorded — Score ${latestAttempt.scorePct}%.`
                      : latestAttempt.passingScorePct !== undefined
                        ? `Defense Not Passed — ${latestAttempt.scorePct}% is below the ${latestAttempt.passingScorePct}% threshold.`
                        : `Defense Recorded — Score ${latestAttempt.scorePct}%.`}
                  </span>
                </div>
                <p className="text-[11px] text-foreground-muted pl-6 leading-relaxed">
                  {latestAttempt.passed
                    ? 'Next: carry on with your preparation topics, or launch another defense to raise the score.'
                    : 'Next: review your recorded answers below, then launch the defense again or review preparation notes.'}
                </p>
              </div>

              {!latestAttempt.passed && (
                <button
                  type="button"
                  onClick={() =>
                    onNavigateToRemediation('preparation', 'prep-interview-career')
                  }
                  className="sm:self-center inline-flex items-center gap-1.5 px-3 py-1.5 rounded-[4px] bg-status-warning/20 hover:bg-status-warning/30 text-status-warning border border-status-warning/40 text-xs font-medium transition-colors shrink-0 cursor-pointer"
                >
                  <span>Review Notes (prep-interview-career)</span>
                  <ArrowRight className="size-3" />
                </button>
              )}
            </div>
          )}

          {/* Historical Attempts Ledger */}
          <div className="space-y-2.5">
            {projectAttempts.map((attempt, index) => {
              const attemptSession = practiceSessions.find(
                (s) => s.id === attempt.sessionId
              );
              const summary = attemptSession
                ? summarizePracticeAnswers(attemptSession, attempt)
                : null;
              const isReviewing = reviewAttemptId === attempt.id;
              const isLatest = index === 0;

              return (
                <div
                  key={attempt.id}
                  className={`bg-[#161E19] border rounded-[6px] text-xs transition-colors overflow-hidden ${
                    isLatest
                      ? 'border-[#0D9488]/40 shadow-xs'
                      : 'border-[#28352D] hover:border-[#3B4C40]'
                  }`}
                  data-testid={`attempt-card-${attempt.id}`}
                >
                  {/* Attempt Summary Row */}
                  <div className="p-3.5 sm:p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                    <div className="space-y-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        {isLatest && (
                          <span className="text-[9px] font-mono font-bold px-1.5 py-0.2 rounded bg-[#0D9488]/20 text-[#2DD4BF] border border-[#0D9488]/40 uppercase tracking-widest">
                            Latest
                          </span>
                        )}
                        <span className="font-semibold text-foreground text-xs">
                          {attempt.sessionTitle || 'System & Project Architecture Defense'}
                        </span>
                        <span className="text-[10px] font-mono text-secondary">
                          (ID: {attempt.id})
                        </span>
                      </div>

                      <div className="flex items-center gap-3 text-[10px] text-foreground-muted font-mono">
                        <span className="flex items-center gap-1">
                          <Clock className="size-3 text-secondary" />
                          {attempt.date}
                        </span>
                        <span>•</span>
                        <span className="text-secondary">
                          Completed {attempt.completedAt}
                        </span>
                        {attempt.evidenceLogId && (
                          <>
                            <span>•</span>
                            <span className="text-[#0D9488]">
                              Log: {attempt.evidenceLogId}
                            </span>
                          </>
                        )}
                      </div>
                    </div>

                    <div className="flex items-center justify-between sm:justify-end gap-3 font-mono shrink-0">
                      <div className="text-left sm:text-right">
                        <div className="flex items-center sm:justify-end gap-1.5">
                          <span className="text-xs font-bold text-foreground">
                            {attempt.scorePct}% Score
                          </span>
                          <span className="text-[10px] text-foreground-muted">
                            ({attempt.correctCount}/{attempt.totalQuestions} correct)
                          </span>
                        </div>

                        <div className="flex items-center sm:justify-end gap-2 mt-0.5">
                          {attempt.passingScorePct !== undefined && (
                            <span
                              className={`text-[10px] font-bold flex items-center gap-1 ${
                                attempt.passed ? 'text-status-success' : 'text-status-danger'
                              }`}
                              data-testid="attempt-verdict"
                            >
                              {attempt.passed ? (
                                <>
                                  <CheckCircle2 className="size-3" />
                                  <span>PASS</span>
                                </>
                              ) : (
                                <>
                                  <XCircle className="size-3" />
                                  <span>FAIL</span>
                                </>
                              )}
                              <span className="text-secondary font-normal">
                                · needs {attempt.passingScorePct}%
                              </span>
                            </span>
                          )}

                          {summary && summary.unansweredCount > 0 && (
                            <span
                              className="text-[10px] text-status-warning font-semibold"
                              data-testid="attempt-unanswered"
                            >
                              · {summary.unansweredCount} unanswered
                            </span>
                          )}
                        </div>
                      </div>

                      <button
                        type="button"
                        onClick={() =>
                          setReviewAttemptId(isReviewing ? null : attempt.id)
                        }
                        aria-expanded={isReviewing}
                        aria-controls={`attempt-audit-${attempt.id}`}
                        className="p-1.5 rounded bg-[#111713] hover:bg-[#161E19] border border-[#28352D] text-foreground-muted hover:text-foreground transition-colors cursor-pointer flex items-center gap-1 text-[11px] font-sans"
                      >
                        <span>{isReviewing ? 'Hide' : 'Review'}</span>
                        {isReviewing ? (
                          <ChevronUp className="size-3.5" />
                        ) : (
                          <ChevronDown className="size-3.5" />
                        )}
                      </button>
                    </div>
                  </div>

                  {/* Question-by-Question Audit Accordion */}
                  {isReviewing && attemptSession && (
                    <div
                      id={`attempt-audit-${attempt.id}`}
                      className="p-3.5 sm:p-4 pt-0 border-t border-[#28352D] space-y-2.5 bg-[#111713]/50"
                      data-testid="attempt-review"
                    >
                      <div className="flex items-center justify-between text-[11px] font-mono text-foreground-muted pt-2">
                        <span className="flex items-center gap-1.5 uppercase font-bold text-[#2DD4BF]">
                          <FileCheck className="size-3.5" />
                          Question-by-Question Verification Audit
                        </span>
                        <span>{attemptSession.questions.length} Prompts Evaluated</span>
                      </div>

                      <ol className="space-y-2.5">
                        {attemptSession.questions.map((q, idx) => {
                          const ans = attempt.userAnswers?.find(
                            (a) => a.questionId === q.id
                          );
                          const answered =
                            typeof ans?.selectedOption === 'number' ||
                            (typeof ans?.userResponse === 'string' &&
                              ans.userResponse.trim().length > 0);
                          const selectedText =
                            typeof ans?.selectedOption === 'number' && q.options
                              ? q.options[ans.selectedOption]
                              : undefined;

                          return (
                            <li
                              key={q.id}
                              className="p-3 bg-[#161E19] border border-[#28352D] rounded-[4px] space-y-2 text-xs"
                            >
                              <div className="flex items-start justify-between gap-2">
                                <span className="text-foreground font-medium leading-snug">
                                  {idx + 1}. {q.prompt}
                                </span>
                                {answered && (
                                  <span
                                    className={`text-[10px] font-mono font-bold px-1.5 py-0.2 rounded shrink-0 ${
                                      ans?.isCorrect
                                        ? 'bg-status-success/15 text-status-success border border-status-success/30'
                                        : 'bg-status-danger/15 text-status-danger border border-status-danger/30'
                                    }`}
                                  >
                                    {isObjectiveQuestionType(q.questionType)
                                      ? ans?.isCorrect
                                        ? 'Correct'
                                        : 'Incorrect'
                                      : ans?.isCorrect
                                        ? 'Self-certified correct'
                                        : 'Not self-certified as correct'}
                                  </span>
                                )}
                              </div>

                              {!answered ? (
                                <span
                                  className="text-[11px] text-status-warning font-semibold block font-mono"
                                  data-testid="answer-unanswered"
                                >
                                  [!] Not answered / Skipped
                                </span>
                              ) : (
                                <div className="space-y-1">
                                  <span className="text-[11px] text-foreground-muted block">
                                    <strong className="text-secondary font-mono">
                                      Candidate Response:
                                    </strong>{' '}
                                    <span className="text-foreground">
                                      {selectedText ?? ans?.userResponse}
                                    </span>
                                  </span>
                                </div>
                              )}

                              {q.explanation && (
                                <div className="p-2.5 bg-[#111713] border border-[#28352D] rounded text-[11px] text-foreground-muted space-y-0.5">
                                  <span className="font-mono font-bold text-[#0D9488] block text-[10px] uppercase tracking-wider">
                                    Model Answer & Explanation:
                                  </span>
                                  <p className="leading-relaxed">{q.explanation}</p>
                                </div>
                              )}
                            </li>
                          );
                        })}
                      </ol>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};
